changelog:
  categories:
    - title: '🚀 Features'
      labels:
        - '🚀 feature'
    - title: '💪 Enhancement'
      labels:
        - '💪 enhancement'
    - title: '🪲 Bug Fixes'
      labels:
        - '🪲 bug'
    - title: '🧰 Maintenance'
      labels:
        - '🧰 chore'
    - title: '🔧 Refactoring'
      labels:
        - '🔧 refactor'
    - title: '📖 Documentation'
      labels:
        - '📖 documentation'
    - title: '⛓️ Dependency update'
      labels:
        - '⛓️ dependencies'
